# Generated by Django 5.0.3 on 2024-04-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contract_id_event_delete_evenement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Evenement',
        ),
    ]
