# Generated by Django 5.0.3 on 2024-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_event_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
