# Generated by Django 5.0.3 on 2024-05-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_evenement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contract'),
        ),
    ]
