# Generated by Django 5.0.3 on 2024-05-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_client_id_evenement_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='support_contact',
        ),
    ]
