# Generated by Django 5.0.3 on 2024-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_evenement_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('signed', 'Signed'), ('not_signed', 'Not Signed')], max_length=10),
        ),
    ]
